CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED auto_increment PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password text NOT NULL,
  type INTEGER UNSIGNED,
  CREATED_AT DATETIME NOT NULL,
  UPDATED_AT DATETIME NOT NULL
);