CREATE TABLE IF NOT EXISTS specialists (
  id BIGINT UNSIGNED auto_increment PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  CREATED_AT DATETIME NOT NULL,
  UPDATED_AT DATETIME NOT NULL,
  CONSTRAINT fk_specialists_on_user_id
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);